---
title: "Methods"
# author: 
#   - name: "Scott Forrest"
#     url: https://swforrest.github.io/
#     orcid: 0000-0001-9529-0108
#     affiliation: Queensland University of Technology, CSIRO
#     email: "scottwforrest@gmail.com"
date: today
execute: 
  cache: false
bibliography: paperpile_references.bib
toc: true
number-sections: false
format: 
  html:
    self-contained: true
    code-fold: show
    code-tools: true
    df-print: paged
    code-line-numbers: true
    code-overflow: scroll
    fig-format: png
    fig-dpi: 300
  pdf:
    geometry: 
      - top=30mm
      - left=30mm
editor:
  source
abstract: |

---

Here we have resources and links for common movement ecology methods that you might want to use. 

**<<< Click the tabs to the left to get information and resources for specific methods.**

Below are some general resources, such as books and workshops with online resources, to give a general overview of movement ecology methods and concepts.

## Books

### Techniques and Concepts in Movement Ecology: With applications in R 
*Authors:* E. Gurarie, N. Barbour, O. Couriot, others.

This book is still being developed, but it gives an excellent overview of animal movement and statistical concepts. It is freely accessible online at <https://eligurarie.github.io/MovementEcologyBook/>.

## Online workshops

### HKU Movement Ecology in R Workshop
*Contributors:* Dana Paige Seidel, Eric Dougherty, Wayne M. Getz

This is a fantastic online resource that covers a range of approaches, also providing code for a variety of movement ecology methods. It was developed in 2018 so there have been methodological developments since then, but it still looks to be robust. Available at <https://www.danaseidel.com/MovEco-R-Workshop/>

## Review papers

Florko, K. R. N., Togunov, R. R., Gryba, R., Sidrow, E., Ferguson, S. H., Yurkowski, D. J., & Auger-Méthé, M. (2025). **An introduction to statistical models used to characterize species-habitat associations with animal movement data**. Movement Ecology, 13(1), 27. https://doi.org/10.1186/s40462-025-00549-2

Joo, R., Boone, M. E., Clay, T. A., Patrick, S. C., Clusella-Trullas, S., & Basille, M. (2020). **Navigating through the r packages for movement**. The Journal of Animal Ecology, 89(1), 248–267. https://doi.org/10.1111/1365-2656.13116

