---
title: "Revisitation analysis"
# author: 
#   - name: "Scott Forrest"
#     url: https://swforrest.github.io/
#     orcid: 0000-0001-9529-0108
#     affiliation: Queensland University of Technology, CSIRO
#     email: "scottwforrest@gmail.com"
date: today
execute: 
  cache: false
bibliography: ../paperpile_references.bib
toc: true
number-sections: false
format: 
  html:
    self-contained: true
    code-fold: show
    code-tools: true
    df-print: paged
    code-line-numbers: true
    code-overflow: scroll
    fig-format: png
    fig-dpi: 300
  pdf:
    geometry: 
      - top=30mm
      - left=30mm
editor:
  source
abstract: |
  
---

## recurse package

The `recurse` R package can be used to analyse revisitation patterns in animal movement data. It provides functions to identify and quantify the number of times an animal returns to specific locations, as well as the duration of stays at those locations. This can be useful for understanding habitat use, foraging behavior, and territoriality.

#### Recurse vignette (tutorial)
<https://cran.r-project.org/web/packages/recurse/vignettes/recurse.html>

#### Key reference
Bracis, C., Bildstein, K. L., & Mueller, T. (2018). **Revisitation analysis uncovers spatio-temporal patterns in animal movement data**. Ecography, 41(11), 1801–1811. https://doi.org/10.1111/ecog.03618

#### Application paper

Campbell, H. A., Loewensteiner, D. A., Murphy, B. P., Pittard, S., & McMahon, C. R. (2020). **Seasonal movements and site utilisation by Asian water buffalo (Bubalus bubalis) in tropical savannas and floodplains of northern Australia**. Wildlife Research , 48(3), 230–239. https://doi.org/10.1071/WR20070


